### ISSUE TITLE
Display job description on jobs page

### ISSUE THREAD

**Issue by rhodebump** [jamescookie/quartz-monitor#28]
I love this plugin!  Thanks.

This is just an enhancement request.

My jobs are listed on the jobs page.  The names of the classes are displayed for each job.  It would be nice if you could use a property that is part of the Job class that displays a more human friendly name.

For example:

class ConstantContactListSyncJob {
  def description = "Synchronization of contacts between constant contact and POS"
}

Right now, ConstantContactListSyncJob  is listed on the jobs page, where I would prefer to see "Synchronization of contacts between constant contact and POS"

Thanks!

**Comment by bwilson** [comment]
I second this request!

**Comment by jamescookie** [comment]
I have done the [code](https://github.com/jamescookie/quartz-monitor/commit/f0d146e5f5c4865e19b581d27c5d79110ce5969c), just waiting to find out what is happening with the [releases](https://groups.google.com/forum/#!topic/grails-dev-discuss/chZPiIP1ZFo) before attempting another one...

**Comment by bwilson** [comment]
Cool, thanks.

**Comment by bwilson** [comment]
Nothing but crickets over at grails dev.

**Comment by anshbansal** [comment]
@jamescookie  Why not start an issue in grails repo? Might get some more attention.

**Comment by anshbansal** [comment]
It seems that bintray has been updated.
https://bintray.com/jamescookie/plugins/org.grails.plugins%3Aquartz-monitor/view

**Comment by jamescookie** [comment]
Never did find out if it published properly to the old plugin repo, but it is certainly in bintray, so closing this issue.
