### ISSUE TITLE
Support Grails 3

### ISSUE THREAD

**Issue by zyro23** [jamescookie/quartz-monitor#29]
given Grails-3.0.0 just reached M2 and a final is planned to be released soon, it would be nice to see this plugin work with Grails 3 :)

(grails3-plugins fork of quartz plugin can be found here: https://github.com/grails3-plugins/quartz)

thanks, zyro

**Comment by jamescookie** [comment]
I will look at creating a new version soon.

**Comment by zyro23** [comment]
please see https://github.com/zyro23/quartz-monitor/tree/grails3 for an initial attempt to move to grails-3.

maybe you want to pull that over into a grails3 branch in your repo as well so i can pull-request against that in case there are further changes needed until we get it into a releaseable state.

changes that i made (besides the usual migration stuff from grails 2 to 3):
* removed configurability of `showCountdown` and `showTickingClock` (if those conditional js includes are still required, i am sure there is a clean way with asset-pipeline, too)
* removed the session flushing/-check (looked like it had a hard dependency in the code on hibernate 3... if that has to be supported, i think the required code/approach can be found in the quartz plugin which has to abstract from hibernate3/hibernate4 as well)
* renamed `QuartzController` to `QuartzMonitorController` (that may be just temporarily until https://github.com/grails/grails-core/issues/607 is fixed but i dont mind if it stays this way)

and also i did not include the gradle grailsCentral/bintray configurations because i do not know how you are planning to release it.

zyro

**Comment by jamescookie** [comment]
Thanks for your efforts, but there is so much in your commit that I am unable to see what is going on. It's important for me to know how the migration works so I will create a grails3 branch and start work on this.
Two of your points:
1) I have just released v1.1 which gets around the problem of the conditional JS
2) The hibernate flushing is a crucial part of why I wrote this plugin in the first place, removing it is not an option. It *is* currently abstract as you can see if you run the 'test-harness-no-hibernate' project (it just looks pretty nasty in the code)

**Comment by zyro23** [comment]
first of all i am happy too see this is now getting attention from you. thanks a lot.

reg. the approach: just do as you think works best. use my fork as draft/orientation/not at all - as you like. n.b. i doubt you will end up with smaller commits because afaik there is no step-by-step migration possible for grails 2 plugins to grails 3 plugins. at some point, you have to switch to the new structure which makes up the majority of the "size" of that commit.

hibernate session flushing: is it possible that you initially created the plugin when the quartz plugin did not yet leverage a `persistenceInterceptor`? please have a look at https://github.com/grails3-plugins/quartz/blob/master/src/main/groovy/grails/plugins/quartz/listeners/SessionBinderJobListener.java - it does already flush/clear the `Session`s of all `persistenceInterceptor`-registered `DataSource`s after the job execution. or am i missing some point there? if so, please tell me =)

**Comment by jamescookie** [comment]
You're right, the [initial commit](https://github.com/jamescookie/quartz-monitor/commit/3fe3523621e4deabefccb9072ae0d90ad311e1cf) to the grails3 branch was pretty large!

Indeed this plugin was written before the quartz plugin had that capability (and it's good that it does), however, the point of this plugin is to report on the success/failure of any job. As the SessionBinderJobListener swallows all the exceptions, it would not be possible to find out what the problem was. That said, it looks like a neater solution to use PersistenceContextInterceptor, and I might migrate to that method once the move to grails 3 is complete.

**Comment by jamescookie** [comment]
V1.2 now works with my grails 3 test project. I have submitted the request for it to be included in https://bintray.com/grails/plugins. Should hopefully be available soon.
