### ISSUE TITLE
Incompatible with Grails 2.5.0

### ISSUE THREAD

**Issue by mamsterla** [jamescookie/quartz-monitor#30]
The new Groovy 2.4.3 introduces issues with @Override

|Compiling 133 source files
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] C:\Users\mamster\.grails\2.5.0\projects\icp2\plugins\quartz-monitor-1.0\src\groovy\grails\plugins\quartz\QuartzMonitorJobFactory.groovy: 19: createJobInstance(org.quartz.spi.TriggerFiredBundle -> org.quartz.spi.TriggerFiredBundle) in grails.plugins.quartz.QuartzMonitorJobFactory cannot override createJobInstance in grails.plugins.quartz.GrailsJobFactory; attempting to assign weaker access privileges; was public
  [groovyc]  @ line 19, column 5.
  [groovyc]        protected Object createJobInstance(TriggerFiredBundle bundle) throws Exception {
  [groovyc]        ^
  [groovyc] 
  [groovyc] 1 error

**Comment by jamescookie** [comment]
Just updated the plugin to v1.1, in which I have made several changes to ensure it runs under a grails 2.5.0 project. Although I did not change anything specifically around the QuartzMonitorJobFactory, I have tested it and confirmed that it works as expected.
