### ISSUE TITLE
Support for grails-schwartz plugin

### ISSUE THREAD

**Issue by robertoschwald** [jamescookie/quartz-monitor#38]
Grails Schwartz is also very popular for quartz scheduling in Grails3.

**Comment by robertoschwald** [comment]
I've created a Grails Quartz plugin agnostic version, which supports the Quartz and Schwartz plugins. Interested in it? If yes, I send a PR.

**Comment by jamescookie** [comment]
Happy to take a look

**Comment by robertoschwald** [comment]
See #42 which is open since JUN/01/17.
