### ISSUE TITLE
How to integrate with Spring Security?

### ISSUE THREAD

**Issue by Guito** [jamescookie/quartz-monitor#45]
I want to use the plugin with spring security, so only some roles can access /quartz. Is it possible to do it? How?

**Comment by jamescookie** [comment]
Some hint of versions etc would be helpful, but you probably need something like this in your application.groovy:

```
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
...
	[pattern: '/quartz/**', access: ['ROLE_ADMINISTRATOR']],
...
]
```
